
@baseUrl = http://localhost:3000
### Create a film 
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Bleach",
    "duration": 200,
    "budget": 517,
    "link": "https://fr.wikipedia.org/wiki/Naruto_Shippuden:_Blood_Prison"
}

### Delete a film
DELETE {{baseUrl}}/films/2


### READ all the films
GET {{baseUrl}}/films
